Added a metrics table
isselab/HAnS pull request #51
Opened 2024-03-12 19:04 UTC by LucaKramer

## Description

Added a Metrics View Table that Lists all Features, with their Scattering Degree, Tangling Degree and Line Count in a table that can be access from the bottom menu next to the Terminal

## Related Issue

## Motivation and Context

## How Has This Been Tested?

- [ ] Tests are created and passing
- [x] Manual testing

## Screenshots (if appropriate):
![image](https://github.com/isselab/HAnS/assets/34602060/6e1bb8c7-4fe8-4da1-905b-083d7a48c5c9)

## Types of changes

- [ ] Pipeline changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] I have updated the [CONTRIBUTORS] file.
- [x] I have updated the [CHANGELOG].

[CONTRIBUTORS]: https://github.com/isselab/HAnS/blob/main/CONTRIBUTORS.md
[CHANGELOG]: https://github.com/isselab/HAnS/blob/main/CHANGELOG.md

2024-03-14 09:05 UTC, johmara requested changes
Looks good in general!

2024-03-14 09:05 UTC, johmara commented on src/main/java/se/isselab/HAnS/metricsView/MetricsViewFactory.java
> +        for (FeatureModelFeature feature : features) {
I think this for should probably be broken out to it's own method to reduce the complexity of this method

2024-03-14 09:05 UTC, johmara commented on src/main/java/se/isselab/HAnS/metricsView/MetricsViewFactory.java
> +        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel);
Probably break this out as well

2024-03-14 09:05 UTC, johmara commented on src/main/resources/META-INF/plugin.xml
> +
don't forget to add copyright to the top of this file

2024-03-14 09:05 UTC, johmara commented on CHANGELOG.md
> +- Added a View of the metrics to the project
Rather make a ned header called `Added`

2024-03-14 09:06 UTC, johmara commented on src/main/resources/META-INF/plugin.xml
> +
Can you also add the icon so it can be seen on the bottom tab in the bottom?

2024-03-14 09:38 UTC, LucaKramer commented on src/main/java/se/isselab/HAnS/metricsView/MetricsViewFactory.java
> +            public void actionPerformed(ActionEvent e) {
Yes currently it only be populated when the button is pressed, as I wasn't able to get it run after the Model was loaded.

2024-03-14 09:58 UTC, johmara commented on src/main/java/se/isselab/HAnS/metricsView/MetricsViewFactory.java
> +    private JBTable createTable(DefaultTableModel tableModel) {
I would prefer if this method was only for Creating the sorters. The table creation can be in the original method.

2024-03-14 10:04 UTC, johmara commented on src/main/java/se/isselab/HAnS/metricsView/MetricsViewFactory.java
> +    private void createSorters(DefaultTableModel tableModel, JBTable table) {
Why not return the sorter so the table is not needed as a parameter?

2024-03-15 12:38 UTC, johmara approved these changes
Approved. We will file another issue that should look into fixing the load of the content at a later stage :)

2024-03-18 11:04 UTC, merged